project:
  type: website

website:
  title: "Tracy Anyasi"
  navbar:
    left:
      - href: about.qmd
        text: About Tracy
      - href: projects.qmd
        text: My Projects
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



