project:
  type: website

website:
  title: "Tracy Anyasi"
  navbar:
    left:
      - href: about.qmd
        text: About Tracy
      - Projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



